config/routes.rb
Rails.application.routes.draw do
  root "hello#index"
  resources :user_registration_authentications

  resources :user_account_lockings do
    post 'lock_account', on: :member
    post 'unlock_account', on: :member
  end
  get "user_profiles/show", to: 'user_profiles#show'
  # とりあえずshowアクションにルーティング。後で直す
  resources :user_account_trackings, only: [:show]
  # とりあえずnew と create アクションに対するルートを設定
  resources :user_password_reset_requests, only: [:new, :create]
  # とりあえずnew と create アクションに対するルートを設定
  resources :user_registrations, only: [:new, :create]
 # 質問関連
 resources :questions, only: [:index, :new, :create, :show]
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id', class_name: 'User'
  belongs_to :question
  has_many :reactions
  has_many :answers_tags
  has_many :tags, through: :answers_tags

  validates :title, presence: true
  validates :question_body, presence: true
end

app/models/answers_tag.rb
class AnswersTag < ApplicationRecord
  belongs_to :answer
  belongs_to :tag
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :questions

  validates :category_name, presence: true, uniqueness: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id', class_name: 'User'
  belongs_to :category
  has_many :answers

  validates :title, presence: true
  # 質問のbodyの長さは500文字以内と以内とする
  validates :question_body, presence: true, length: { maximum: 500 }
end

app/models/question_tag.rb
class QuestionTag < ApplicationRecord
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :answer
  belongs_to :user
  has_many :stamps
end

app/models/stamp.rb
class Stamp < ApplicationRecord
  belongs_to :reaction
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :question_tags
  has_many :questions, through: :question_tags
  has_many :answers_tags
  has_many :answers, through: :answers_tags

  validates :tag_name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions, foreign_key: 'user_id'
  has_many :answers, foreign_key: 'user_id'
  has_many :reactions
end

app/models/user_account_locking.rb
class UserAccountLocking < ApplicationRecord
  belongs_to :user
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  def show
    @user = User.find(params[:id])
  end
end

app/models/user_registration.rb
class User::UserRegistration < ApplicationRecord
end

app/models/user_registration_authentication.rb
class UserRegistrationAuthentication < ApplicationRecord
  belongs_to :user
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/user_registration_authentications_controller.rb
class UserRegistrationAuthenticationsController < ApplicationController
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/user_registration_authentications_helper.rb
module UserRegistrationAuthenticationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_registration_authentications/new.html.erb
<!-- app/views/user_registration_authentications/new.html.erb -->

<h1 class="display-4">新規ユーザー登録</h1>

<%= form_with model: @user, url: user_registration_authentications_path, method: :post, class: "needs-validation" do |f| %>
  <div class="mb-3">
    <%= f.label :user_name, 'ユーザー名', class: "form-label" %>
    <%= f.text_field :user_name, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= f.label :email, 'メールアドレス', class: "form-label" %>
    <%= f.email_field :email, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= f.label :password, 'パスワード', class: "form-label" %>
    <%= f.password_field :password, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= f.label :password_confirmation, 'パスワード確認', class: "form-label" %>
    <%= f.password_field :password_confirmation, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= f.submit '登録', class: "btn btn-primary" %>
  </div>
<% end %>